### ISSUE TITLE
Creating multiple Mai Ads doesn't work

### ISSUE THREAD

**Issue by shay328** [maithemewp/mai-ads-manager#7]
Updating more than one Mai Ad doesn't always work. 

For example, if I create 10 ads then update, only the last entry is saved and the other 9 disappear. 

It works when I save after creating each one.

**Comment by JiveDig** [comment]
I have code generating a random ID for each ad (repeater row) but it looks like it doesn't change the id when generating a new row. I'm going to change it so it generates the ID on save instead. That field is readonly so it can't be edited, I just have to make it not required now so it can save while empty.
